#!/bin/bash

# bashrc
# Copy bashrc to ~/.bashrc and source

cp bashrc* ~/.bashrc
echo "bashrc# copied to ~/.bashrc"

. ~/.bashrc
echo "bashrc# sourced to current shell"

# vim
# Copy vim to $HOME and source via vim

cp vimrc* ~/.vimrc # vimrc* so that vimrc2-3-4 copies!
echo "vimrc# copied to ~/.vimrc"

echo "vimrc# to ~/.vimrc, to source use ":so ~/.vimrc" within vim"
