#!/bin/bash

# Description: Link dotfiles to home directory.

link_file(){
	local src="$1"
	local dest="$2"
	ln -sf "$src" "$dest"
	echo "Linked: $dest"

}

dotfiles=("bashrc" "vimrc")

for file in "${dotfiles[@]}"; do
	link_file "$HOME/dotfiles/$file" "$HOME/.$file"
done

# ln -sf ~/dotfiles/starhip.toml ~/.config/starhip.toml

echo "dotfiles linked!!!"
