#!/bin/bash

print_numbered() {
	local items=("$@")
	local i=1
	for item in "${items[@]}"; do
		echo "$i. $item"
		((i++))
	done
}

tasks=("buy milk" "vacuum house" "work hard")
print_numbered "${tasks[@]}"


